Synphonyte/leptos-use

docs/book/src/get_started.md

Hello,
I just wanted to draw attention to this deprecated part of the getting started section. Feel free to reword it in any way appropriate. But I am sure I am not the only one that prefers to use stable rust, especially for trying out the libraries.

Stable Rust docs

---

examples/use_service_worker/Trunk.toml
examples/use_service_worker/post_build.sh

I've been having trouble building the mdbook with `python3 post_build.py`. This was failing for two reasons.
The first was that bash was being called with a command string "./post_build.sh" for the use_service_worker. I've changed this to rely on calling the file directly by removing -c option. The second was that the bash script was relying on `#! /bin/bash`. I'm on NixOS which doesn't have a /bin/bash.
So this PR should make the mdbook build scripts more portable.

Problem: mdbook use_service_worker script is not portable

---

.github/workflows/book.yml
.github/workflows/ci.yml
examples/use_storage/src/main.rs
src/use_broadcast_channel.rs

- Install Trunk v0.17.5, next versions are breaking the build because they are not generating the starting `<head>` element on examples.
- Apply clippy suggestions.

Use previous Trunk version in CI and apply clippy suggestions

---

src/core/element_maybe_signal.rs
src/core/elements_maybe_signal.rs
src/math/shared.rs
src/use_breakpoints.rs
src/use_cycle_list.rs
src/use_infinite_scroll.rs
src/use_sorted.rs

Use [`impl Fn() -> T + 'static`](https://docs.rs/leptos/latest/leptos/struct.Signal.html#method.derive) instead of [`impl Fn(Option<&T>) -> T + 'static`](https://docs.rs/leptos/latest/leptos/fn.create_memo.html) when possible.

Prefer signals over memos with first unused argument when possible

---

docs/book/src/demo.css
src/use_clipboard.rs

The "Source" button of the clipboard demo can't be easily clicked at https://leptos-use.rs/browser/use_clipboard.html

Fix `.demo-source` docs links

---

Cargo.toml
src/core/mod.rs
src/core/url.rs
src/storage/use_storage.rs
src/use_color_mode.rs

Closes #78
I'm not sure if this is the best way to implement it, but seems to work fine. Suggestions would be appreciated.

Add options to discover initial color mode from URL param

---

docs/book/src/server_side_rendering.md

I wasn't aware of Leptos' SSR build process, and enabled the `leptos-use` feature globally. Because of this I ended up with the server version of the functions in the client, which obviously did not work.
See #83 for context.

Add ssr feature note to the book

---

CHANGELOG.md
src/core/url.rs

I missed that on #79. Currently panics when compiling if `initial_value_from_url_param` is `true` on the server.

Fix SSR detection from an url query parameter for `use_color_mode`

---

examples/use_cookie/src/main.rs
src/use_cookie.rs

Setting `document.cookie` only supports [setting a single cookie at a time](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie). Currently `use_cookie` will try to set multiple cookies by serializing the whole cookie jar. This PR fixes setting and deleting cookies from the client, and adds a second counter to the `use_cookie` example. This example is broken with the current `use_cookie` implementation and works correctly in this branch.
Unfortunately `cookie` uses `time` so `jar.remove` doesn't work in WASM, which makes the implementation a bit awkward (have to first add the cookie with value="" and expires=0, and then afterward call `jar.force_remove`)

Fix document.set_cookie usage

---

CHANGELOG.md
src/use_cookie.rs

The original messages read as requiring both features to be enabled at the same time instead of requiring one or the other - not both - to be enabled.

Fix typo in use_cookie compile errors.

---

src/utils/signal_filtered.rs

Resolves Issue #129 by tracking the caller location of filtered signals for use in "outside reactive context" warnings.

Uses caller tracking for filtered signals for better warning reporting.

---

.github/workflows/cd.yml
.github/workflows/ci.yml

This is a proposal on improving integrity checks for both Rust toolchains `stable` and
`nightly`. This is attempted to be executed before merging a PR.
Basically current `ci.yml` is moved to `cd.yml` as it contains releasing steps,
and `ci.yml` now performs code integration steps.

chore: integrity checks for nightly/stable

---

.cargo/config.toml
src/use_clipboard.rs

Resolves #105. See https://github.com/rust-lang/cargo/issues/9138#issuecomment-774074873

Fix `web_sys_unstable_apis` not passed to rustdoc

---

src/use_web_notification.rs

Prior to `wasm-bindgen v0.2.93`, `#[wasm_bindgen]` on an enum made it "non-exhaustive" by adding a `__Nonexhaustive` variant, with the new release of `v0.2.93` it does'nt introduce that variant anymore and just use `#[non_exhaustive]`. This PR solves this issue, for both prior versions and incoming version of `wasm-bindgen`.
I did a quick search and this is the only instance of the use of this "fake" variant in the codebase.

fixed an error for a match on a non exhaustive enum

---

CHANGELOG.md
src/use_locale.rs
src/use_mouse.rs
src/use_mouse_in_element.rs

I was unhappy with how `UseMouseCoordType` and `UseMouseEventExtractor` were setup, and especially I did not like the "useless" existence of `UseMouseEventExtractorDefault`.
This makes the following changes:
1. `UseMouseEventExtractorDefault` is removed.
2. `UseMouseCoordType<E>` now has a `Default` implementation for the type `UseMouseCoordType<Infallible>`.

Rework of `UseMouseCoordType`

---

Cargo.toml
src/use_websocket.rs

I have a need to use the `protocols` option of websockets, but I can only get them asyncronously. This PR provides a way to have "async" protocols by wrapping `Option<Vec<String>>` in `MaybeSignal`. Combining e.g. an async resource as the protocol signal with `opts.immediate(false)` and manually calling `ws.open()` once the resource has loaded solves the issue.
This is definitely a weird implementation though, if you have a better way to do it I can update the PR?
This shouldn't be a breaking change, all previous config of the protocol option should be unaffected, due to the `impl Into<MaybeSignal<...>>`

Allow for lazy protocols with use_websocket

---

src/utils/header.rs

For the Send/Sync changes in Leptos, `actix_web::HttpRequest` is now wrapped in `leptos_actix::Request`
I've only looked into actix, I don't know if anything changed with axum or spin.

Fix the request context for actix web

---

Cargo.toml

After  #183 (Thanks, BTW!), the crate does not build with `--no-default-features --features use_user_media`. It looks like the `web-sys/MediaTrackConstraints` dependency accidentally ended up in the `use_web_notification` feature block. I swapped it to `use_user_media` block and tested with:
```shell
cargo build --no-default-features --features use_user_media && \
cargo build --no-default-features --features use_web_notification
```

Fix MediaTrackConstraints dependency

---

src/docs/boolean_display.rs
src/math/shared.rs
src/math/use_not.rs
src/use_css_var.rs
src/use_cycle_list.rs
src/use_debounce_fn.rs
src/use_draggable.rs
src/use_interval.rs
src/use_interval_fn.rs
src/use_intl_number_format.rs
src/use_media_query.rs
src/use_scroll.rs
src/use_sorted.rs
src/use_throttle_fn.rs
src/use_timeout_fn.rs
src/use_websocket.rs
src/utils/filters/debounce.rs
src/utils/filters/mod.rs
src/utils/filters/throttle.rs
src/utils/signal_filtered.rs
src/watch_debounced.rs

I was taking a look at this project and kept getting a bunch of warnings when I ran `cargo check`. This PR fixes all the warnings from running `cargo check` and `cargo clippy`.

Fix Clippy Warnings for Leptos 0.7

---

Cargo.toml
src/is_none.rs
src/is_some.rs
src/sync_signal.rs
src/use_active_element.rs
src/use_cookie.rs
src/use_display_media.rs
src/use_service_worker.rs
src/use_user_media.rs

Unpin `wasm-bingen` to be compatible with `leptos-0.7.0-rc1`. See https://github.com/leptos-rs/leptos/pull/3186.
Fixes https://github.com/Synphonyte/leptos-use/issues/176

Unpin `wasm-bindgen` version

---

Cargo.toml

This PR unpins the `web-sys` crate version to be in sync with `leptos`.

fix: unpinning web-sys

---

src/use_locale.rs

Currently, on `use_locale`, if the server receives a malformed `Accept-Language` header, it will panic: <https://github.com/Synphonyte/leptos-use/blob/a1bac85023e26a3079a19657d687e27cfadfeeed/src/use_locale.rs#L79>
Changed it so the offending language (or the entire header, see `use_locales`) is ignored and a warning is logged instead.
The current implementation will also panic if there are no client languages whatsoever. Fixed that case too.
I tried to do it in such a way as to minimize clones.

Prevent crashes on `use_locale`

---

src/use_locale.rs

This builds upon #199, because the code overlaps.
Currently, the matching algorithm does it best to try to match the first _supported_ languages, instead of prioritizing matching the first _client_ languages, which would be the more useful behavior.
So, for example, if the user declares it accepts Chinese first, English second; but the application support English first, Chinese second; then, the first supported language, English, will be matched, even though the user would prefer Chinese.
This change inverts the order in which the languages are checked so that the supported languages are exhausted before moving to the next client one.
I'm assuming the `clone` on the Peekable iterator is cheap, but honestly I'm not entirely sure.

Fix order of language checks in `use_locale`

---

CHANGELOG.md
Cargo.toml
examples/Cargo.toml
examples/ssr/Cargo.toml

The [first stable version of Leptos 0.7](https://github.com/leptos-rs/leptos/releases/tag/v0.7.0) was just released, so I figure I'd take the liberty of bumping the dependency.
I also updated the `wasm-bindgen` and `web-sys` crates to their most recent versions.

Update to stable Leptos 0.7

---

src/storage/use_storage.rs

Under some circumstances, the stored value would be overridden by default even with delay_during_hydration.  I don't know what steps reproduce this issue - it occurs in one of my projects and not another project.
Use flag to prevent setting the value before the request_animation_frame callback runs

fix:  More reliable delay during hydration for use_storage

---

Cargo.toml
examples/Cargo.toml
examples/use_cookie/src/main.rs
src/use_color_mode.rs
src/use_cookie.rs
src/use_locales.rs
src/use_preferred_dark.rs
src/use_prefers_reduced_motion.rs
src/utils/header.rs
src/utils/header_macro.rs
src/utils/mod.rs

- Remove references to the `leptos-spin` dependency which hasn't received updates in a while and is still stuck on `leptos@0.6`.
- Update to `rand@0.9`.
This pull request is to keep track track of the `leptos@0.8` updates. 
I'm happy to make changes requested.

Update to `leptos@0.8.0-alpha`

---

Cargo.toml

I noticed that `chrono` is included unconditionally in `leptos-use`'s dependencies. Since chrono is only used by the `use_calendar` feature (as far as I can tell), it would be more efficient to make it an optional dependency and gate it behind the `use_calendar` feature in `Cargo.toml`.
Related:
#232 #255 #254

fix: gate `chrono` by `use_calendar`

---

src/use_color_mode.rs

I keep getting panics from `use_color_mode` in a Axum/SSR app.
Partial stack trace:
```
thread 'tokio-runtime-worker' panicked at /.../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reactive_graph-0.1.8/src/owner/storage.rs:141:34:
Dereferenced SendWrapper<T> variable from a thread different to the one it has been created with.
stack backtrace:
...
at /.../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/reactive_graph-0.1.8/src/traits.rs:728:9
22: <leptos_use::core::element_maybe_signal::ElementMaybeSignal<T> as reactive_graph::traits::WithUntracked>::try_with_untracked
at /.../.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/leptos-use-0.15.8/src/core/element_maybe_signal.rs:126:50
23: <T as reactive_graph::traits::GetUntracked>::try_get_untracked
at …
```

use_color_mode put frontend only logic behind feature gate
