- src/use_active_element.rs
- src/use_element_hover.rs
- src/use_mouse.rs
- src/use_scroll.rs
- src/use_window_scroll.rs
It seems that a few places were not covered with the latest commit.
> Replace all occurrences of AddEventListenerOptions with UseEventListenerOptions

- src/use_websocket.rs
Removes an unnecessary (probably debugging) logging statement.
> Remove logging of WS url

- src/use_cookie.rs
> time unit of cookie's max-age is actually millisecond

- src/is_err.rs
- src/is_none.rs
- src/is_ok.rs
- src/is_some.rs
- src/use_to_string.rs
- src/utils/mod.rs
- src/utils/use_derive_signal.rs
> Make `use_derive_signal!` public

- docs/book/src/demo.css
- src/use_cookie.rs
> Fix: use_cookie demo button misalignment

- src/use_document.rs
Added methods in the order they appear on the website discussed (for convenience) up to `preferred_style_sheet_set`.
@maccesch please let me know how all this looks and I'll keep chipping away at them!
> Add methods to UseDocument

- src/core/element_maybe_signal.rs
- src/use_color_mode.rs
- src/use_timeout_fn.rs
- src/use_web_notification.rs
> Fixed an untyped into causing compilation error

- src/use_cookie.rs
The cookie update while in the `update_value` function was causing a deadlock for the arena access, moved the cookie set outside of the closure.
> Fixed a deadlock with `use_cookie` 

- src/use_websocket.rs
Console error:
```
panicked at /.../.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos-use-0.12.0/src/use_websocket.rs:314:68:
could not get stored value
```
Note:  I tested this as working when cherry-picked into `v0.12.0`, but trying to compile my project with `main` branch fails so this hasn't been able to be testing on main.
> bugfix: error when cleanup happens after reconnect attempt is on timeout

- src/use_websocket.rs
Fixes:  `use of undeclared crate or module 'diagnostics'`
> Fix 0.7 compilation error

- Cargo.toml
`version = "0.7-beta"` pulls in the most current beta crate version - better than using master branch
> Use `version = "0.7-beta"` instead of `git`

- src/storage/use_storage.rs
Fix for breaking change in leptos `0.7-beta5`
> fix: notify from trigger (0.7 beta change)

- src/use_cookie.rs
i noticed the library is unnecessarily setting cookies on the server side and also skipping cookies that should be set on initial page loads
this PR is the fixes i came up with
> ssr cookie bug fixes

- examples/signal_debounced/src/main.rs
> Cleaned up cruft in `signal_debounced` example.

- src/use_drop_zone.rs
in my use case i have to destruct and construct UseDropZoneReturn whenever i want to clone it
and the contents of this struct implement copy anyway so i implemented Copy to make my life easier
> impl Clone + Copy for UseDropZoneReturn

- src/use_mutation_observer.rs
> fix: fix `use_mutation_observer`

- examples/use_websocket/src/main.rs
It looks like there were two method-calls missing.
After adding them the code runs fine.
> Fixed small issue in websocket example

- Cargo.toml
- examples/Cargo.toml
- examples/ssr/Cargo.toml
Keeping track of latest `leptos@0.8.0-beta` releases.
> feat: update to `leptos@0.8.0-beta`

- examples/use_calendar/src/main.rs
- src/use_calendar.rs
- src/use_element_hover.rs
added month_by_date function allowing show arbitrary month by date (useful when building date picker)
> feat: add month_by_date for use_calendar

- src/use_cookie.rs
Fixes https://github.com/Synphonyte/leptos-use/issues/259
> Fixed effects running simultaneously.

- src/use_interval_fn.rs
Guard clean_up behind the ssr flag (Closes: #271)
Without this it panics in SSR mode.
> Guard clean_up behind the ssr flag
